language: python

python:
    - 2.7

install:
    - pip install django==1.7
    - pip install django-registration-redux
    - pip install djangorestframework
    - pip install pillow
    - pip install requests
    - pip install flake8
    - pip install coverage
    - pip install coveralls

script:
    coverage run --source='.' manage.py test

after_success:
    coveralls